### PR TITLE
Deploy Documentation Site

### PR DESCRIPTION
**Pull request by lekiet1214**
…ld and dependencies

## Description

- Integrated documentation site with Cloudflare Pages.
- Added Openapi documentation.

## How Has This Been Tested?

Visit [ezhrchatbot.pages.dev](https://docs-9-deploy-documentation.ezhrchatbot.pages.dev/) for a preview.

## Accepted Risk

None

## Related Issue(s)

#9 #45 

## Checklist:

- [ ] All of the automated tests pass
- [ ] All PR comments are addressed and marked resolved
- [x] If there are migrations, they have been rebased to latest main
- [x] If there are new dependencies, they are added to the requirements
- [x] If there are new environment variables, they are added to all of the deployment methods
- [x] If there are new APIs that don't require auth, they are added to PUBLIC_ENDPOINT_SPECS
- [x] Docker images build and basic functionalities work
- [x] Author has done a final read through of the PR right before merge

### CODE REVIEW

**Comment by lelouvincx** [comment]
Note: handover to @lekiet1214 to use docusaurus instead.

**Comment by lekiet1214** [comment]
@lelouvincx can you review this?
I'll open a new documentation branch for rapid updates.

**Comment by lelouvincx** [comment]
> @lelouvincx can you review this? I'll open a new documentation branch for rapid updates. Possible merge branch #9 and #14

Is it done? Can u send me preview link?

**Comment by lekiet1214** [comment]
> > @lelouvincx can you review this? I'll open a new documentation branch for rapid updates. Possible merge branch #9 and #14
> 
> Is it done? Can u send me preview link?
Site is up at [cloudflare](https://ezhrchatbot.pages.dev/)

**Review by lelouvincx — APPROVED** [review]
That looks nice. Thank you!

**Pull request merged**
